# Generated by Django 4.2.11 on 2025-05-13 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('settledBy', models.CharField(max_length=255, null=True)),
                ('amount_usdc', models.DecimalField(decimal_places=3, max_digits=20)),
                ('amount_fiat', models.DecimalField(decimal_places=3, max_digits=20)),
                ('isClaimed', models.BooleanField(default=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.type')),
            ],
        ),
    ]
