# Generated by Django 4.2.11 on 2025-05-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=255)),
                ('fiat_amount', models.DecimalField(decimal_places=3, max_digits=5)),
                ('usdc_amount', models.DecimalField(decimal_places=3, max_digits=3)),
                ('amount', models.IntegerField()),
                ('issuedBy', models.CharField(max_length=255)),
                ('settledBy', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=255)),
                ('plan', models.CharField(max_length=255)),
                ('fiat_amount', models.DecimalField(decimal_places=3, max_digits=5)),
                ('usdc_amount', models.DecimalField(decimal_places=3, max_digits=3)),
                ('amount', models.IntegerField()),
                ('issuedBy', models.CharField(max_length=255)),
                ('settledBy', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=255)),
                ('meter_number', models.CharField(max_length=255)),
                ('meter_owner', models.TextField()),
                ('fiat_amount', models.DecimalField(decimal_places=3, max_digits=5)),
                ('usdc_amount', models.DecimalField(decimal_places=3, max_digits=3)),
                ('amount', models.IntegerField()),
                ('issuedBy', models.CharField(max_length=255)),
                ('settledBy', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
