# Generated by Django 4.2.11 on 2025-05-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_airtime_data_electricity_delete_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity',
            name='meter_owner',
            field=models.CharField(max_length=255),
        ),
    ]
