# Generated by Django 4.2.11 on 2025-05-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_electricity_meter_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuedByAddr', models.CharField(max_length=255)),
                ('handledByAddr', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('handled_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
