# Generated by Django 4.2.11 on 2025-05-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtime',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
