# Generated by Django 4.2.11 on 2025-05-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_airtime_phone_number_data_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtime',
            name='settledBy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='settledBy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='settledBy',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
