# Generated by Django 4.2.11 on 2025-05-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_alter_airtime_settledby_alter_data_settledby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtime',
            name='fiat_amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='airtime',
            name='usdc_amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='fiat_amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='usdc_amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='fiat_amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='usdc_amount',
            field=models.CharField(max_length=100),
        ),
    ]
