# Generated by Django 4.2.11 on 2025-05-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_alter_airtime_settledby_alter_data_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtime',
            name='isOpen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data',
            name='isOpen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electricity',
            name='isOpen',
            field=models.BooleanField(default=False),
        ),
    ]
