# Generated by Django 4.2.11 on 2025-05-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_airtime_isopen_data_isopen_electricity_isopen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtime',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='settledBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='settledBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
