# Generated by Django 4.2.11 on 2025-05-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_alter_airtime_phone_number_alter_data_settledby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtime',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='airtime',
            name='settledBy',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
