# Generated by Django 4.2.11 on 2025-05-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_alter_airtime_phone_number_alter_airtime_settledby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtime',
            name='isOpen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='isOpen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='electricity',
            name='isOpen',
            field=models.BooleanField(default=True),
        ),
    ]
