# Generated by Django 4.2.11 on 2025-05-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_alter_airtime_isopen_alter_data_isopen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtime',
            name='orderId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='orderId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electricity',
            name='orderId',
            field=models.IntegerField(default=0),
        ),
    ]
