# Generated by Django 4.2.11 on 2025-05-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_airtime_orderid_data_orderid_electricity_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtime',
            name='isFulFilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='airtime',
            name='isReFund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data',
            name='isFulFilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='data',
            name='isReFund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electricity',
            name='isFulFilled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electricity',
            name='isReFund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electricity',
            name='token_number',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
