# Generated by Django 4.2.11 on 2025-05-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_airtime_isfulfilled_airtime_isrefund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity',
            name='token_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
