# Generated by Django 4.2.11 on 2025-05-18 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0015_alter_electricity_token_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricity',
            old_name='token_number',
            new_name='token',
        ),
    ]
