# Generated by Django 4.2.11 on 2025-05-07 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='walletAddress',
            new_name='walletaddress',
        ),
    ]
